import "./script.js"
import "./validateForm.js"
import "./submiteForm.js"
import "../styles/normalize.css"
import "../styles/style.less"
import '../img/intro__bg.png';
import '../img/main__item_item-1.png';
import '../img/main__item_item-2.png';
import '../img/main__item_item-3.png';
import '../img/intro__bg.png';